/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Analizador;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Stack;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        bt_seleccionar = new javax.swing.JButton();
        bt_probar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        bt_guardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextErrores = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_cuadruplos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compilador Mini-C");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        bt_seleccionar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        bt_seleccionar.setText("Seleccionar Archivo");
        bt_seleccionar.setName("bt_seleccionar"); // NOI18N
        bt_seleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_seleccionarMouseClicked(evt);
            }
        });

        bt_probar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        bt_probar.setText("Probar");
        bt_probar.setName("bt_probar"); // NOI18N
        bt_probar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_probarMouseClicked(evt);
            }
        });

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        bt_guardar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        bt_guardar.setText("Guardar");
        bt_guardar.setName("bt_guardar"); // NOI18N
        bt_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardarMouseClicked(evt);
            }
        });

        TextErrores.setColumns(20);
        TextErrores.setRows(5);
        jScrollPane2.setViewportView(TextErrores);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Archivo: ");

        titulo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_seleccionar)
                        .addGap(18, 18, 18)
                        .addComponent(bt_guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                        .addComponent(bt_probar)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(titulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_seleccionar)
                    .addComponent(bt_probar)
                    .addComponent(bt_guardar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Compilador", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        table_cuadruplos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Op", "Arg1", "Arg2", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table_cuadruplos);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cuadruplos:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cuádruplos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_probarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_probarMouseClicked
        try {
            //File file = new File("C:\\Users\\HP\\Desktop\\Periodo actual\\Compi\\Mini-C\\Interfaz\\src\\Analizador\\prb.txt");
            Lexer lexer = new Lexer(new FileReader(fichero));
            ASintactico p = new ASintactico(lexer);
            //System.out.println("**************************************************");
            p.parse();
            System.out.println("**************************************************");
            this.TextErrores.setText("");
            ArrayList<String> lexi = lexer.errores;
            ArrayList<String> l = p.errores;

            //semantico
            tabla.clear();
            funciones.clear();
            decfunciones.clear();
            errores_semanticos.clear();
            TreeNode root = p.Tree;
            recorrer(root);

            int m = verificar_main();
            switch (m) {
                case 0:
                    System.out.println("No existe main");//*******
                    this.errores_semanticos.add("No existe main.");
                    break;
                case 1:
                    System.out.println("Bien");//*******
                    break;
                default:
                    System.out.println("Hay más de 1 main");//*******
                    this.errores_semanticos.add("Hay más de 1 main.");
                    break;
            }

            for (int i = 0; i < tabla.size(); i++) {
                System.out.println("Variable: Tipo = " + tabla.get(i).getTipo() + " , Id = " + tabla.get(i).getId() + " , Ambito = " + tabla.get(i).getAmbito() + " , Offset = " + tabla.get(i).getOffset());
            }
            for (int i = 0; i < funciones.size(); i++) {
                System.out.println("Funcion: Tipo = " + funciones.get(i).getTipo() + " , Id = " + funciones.get(i).getId());
                System.out.println("Parametros:");
                for (int j = 0; j < funciones.get(i).getParams().size(); j++) {
                    System.out.print((j + 1) + " Tipo = " + funciones.get(i).getParams().get(j).getTipo() + " Id = ");
                    System.out.println(funciones.get(i).getParams().get(j).getId() + " Ambito = " + funciones.get(i).getParams().get(j).getAmbito());
                }
            }
            for (int i = 0; i < this.decfunciones.size(); i++) {
                System.out.println("DECFUNC: " + this.decfunciones.get(i).getId());
                for (int j = 0; j < this.decfunciones.get(i).getParams().size(); j++) {
                    System.out.println(this.decfunciones.get(i).getParams().get(j).getTipo());
                }
            }
            //************
            if (l.isEmpty() && lexi.isEmpty() && errores_semanticos.isEmpty()) {
                this.TextErrores.append("Compilado sin errores!");
                //codigo intermedio
                this.cuadruplos.clear();
                this.cont_temp = 0;
                this.cont_etiq = 0;
                codigo_intermedio(root);
                System.out.println("*******CUADRUPLOS*******");

                DefaultTableModel model = (DefaultTableModel) table_cuadruplos.getModel();
                model.setRowCount(0);
                for (int i = 0; i < this.cuadruplos.size(); i++) {
                    model.addRow(this.cuadruplos.get(i).retorno_tabla());
                    System.out.println(this.cuadruplos.get(i).toString());
                }
            }
            for (int i = 0; i < lexi.size(); i++) {
                this.TextErrores.append(lexi.get(i) + "\n");
            }
            for (int i = 0; i < l.size(); i++) {
                this.TextErrores.append(l.get(i) + "\n");
            }
            for (int i = 0; i < errores_semanticos.size(); i++) {
                this.TextErrores.append(errores_semanticos.get(i) + "\n");
            }
        } catch (Exception e) {
            System.out.println("ERROR");
            e.printStackTrace();
        }
    }//GEN-LAST:event_bt_probarMouseClicked

    private void bt_seleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_seleccionarMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            fichero = fileChooser.getSelectedFile();

            FileReader fr = null;
            BufferedReader bf = null;
            try {
                fr = new FileReader(fichero);
                bf = new BufferedReader(fr);
                String linea;
                this.TextArea.setText("");
                this.TextErrores.setText("");
                while ((linea = bf.readLine()) != null) {
                    this.TextArea.append(linea + "\n");
                }
                this.titulo.setText(fichero.getName());
            } catch (Exception e) {
            } finally {
                try {
                    fr.close();
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }

    }//GEN-LAST:event_bt_seleccionarMouseClicked

    private void bt_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarMouseClicked

        FileWriter fichero2 = null;
        PrintWriter pw = null;
        try {
            fichero2 = new FileWriter(fichero.getAbsolutePath());
            pw = new PrintWriter(fichero2);
            pw.print(this.TextArea.getText());
            this.TextErrores.setText("");
            JOptionPane.showMessageDialog(this, "Archivo guardado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado un archivo");
            //e.printStackTrace();
        } finally {
            try {
                if (null != fichero2) {
                    fichero2.close();
                }
            } catch (Exception e2) {
                JOptionPane.showMessageDialog(this, "Ocurrio un error");
                //e2.printStackTrace();
            }
        }

    }//GEN-LAST:event_bt_guardarMouseClicked

    //Metodos
    //semantico
    public void recorrer(TreeNode tn) {
        TreeNode nodo = tn;
        if (nodo != null) {
            if (nodo.getVal().equals("Declaracion")) {
                String tipo = "";
                String id = "";
                for (TreeNode hijo : nodo.getHijos()) {
                    if (hijo.getVal().equals("Tipo")) {
                        tipo = hijo.getHijos().get(0).getVal();
                        if (hijo.getHijos().get(1).getVal().equals("*")) {
                            tipo += "*";
                        }
                    } else if (hijo.getVal().equals("*")) {
                        tipo += "*";
                    } else if (hijo.getVal().equals("ID")) {
                        id += hijo.getHijos().get(0).getVal();
                        if (verificar_variable(id)) {
                            //System.out.println("Error Semántico: La variable '" + id + "' ha sido declarada más de una vez");
                            this.errores_semanticos.add("Error Semántico: La variable '" + id + "' ha sido declarada más de una vez");
                        } else {
                            this.tabla.add(new Variable(tipo, id, this.ambito_actual, this.offset));
                            if (tipo.equals("char")) {
                                this.offset += 1;
                            } else {
                                this.offset += 4;
                            }
                        }
                        if (tipo.contains("*")) {
                            tipo = tipo.substring(0, tipo.length() - 1);
                        }
                        id = "";
                    }
                }
            } else if (nodo.getVal().equals("Funcion")) {
                String tipo_f = "";
                String id_f = "";
                this.offset = 0;
                for (TreeNode hijo : nodo.getHijos()) {
                    if (hijo.getVal().equals("Tipo")) {
                        tipo_f = hijo.getHijos().get(0).getVal();
                        if (hijo.getHijos().size() > 1) {
                            if (hijo.getHijos().get(1).getVal().equals("*")) {
                                tipo_f += "*";
                            }
                        }

                        this.tipo_actual = tipo_f;
                    } else if (hijo.getVal().equals("ID")) {
                        id_f += hijo.getHijos().get(0).getVal();
                        this.ambito_actual = id_f;
                    } else if (hijo.getVal().equals("p") || hijo.getVal().equals("#")) {
                        if (!"".equals(tipo_f)) {
                            ArrayList<Variable> v = parametros(hijo, new ArrayList<>());
                            Funcion func = (new Funcion(tipo_f, id_f));
                            func.agregar_params(v);

                            boolean verificar = false;
                            String ambito1 = "", id1 = "";
                            for (int i = 0; i < v.size() - 1; i++) {
                                for (int j = i + 1; j < v.size(); j++) {
                                    if (v.get(i).id.equals(v.get(j).id) && v.get(i).ambito.equals(v.get(j).ambito)) {
                                        verificar = true;
                                        ambito1 = v.get(i).ambito;
                                        id1 = v.get(i).id;
                                    }
                                }
                            }

                            if (verificar) {
                                System.out.println("Hay parametros que se llaman igual");
                            } else {
                                //System.out.println("No hay parametros que se llamen igual");
                            }

                            if (verificar_funcion(id_f)) {
                                if (!verificar) {
                                    this.funciones.add(func);
                                    for (Variable variable : v) {
                                        tabla.add(variable);
                                    }
                                } else {
                                    this.errores_semanticos.add("La variable " + id1 + " fue definida más de una vez en la función " + ambito1);
                                }

                            } else {
                                //System.out.println("La funcion " + id_f + " fue declarada más de una vez.");
                                this.errores_semanticos.add("La funcion " + id_f + " fue declarada más de una vez.");
                            }

                            tipo_f = "";
                            id_f = "";
                        }
                    } else {
                        recorrer(hijo);
                    }
                }
            } else if (nodo.getVal().equals("DecFuncion")) {
                String tipo_f = "";
                String id_f = "";
                for (TreeNode hijo : nodo.getHijos()) {
                    if (hijo.getVal().equals("Tipo")) {
                        tipo_f = hijo.getHijos().get(0).getVal();
                        if (hijo.getHijos().get(1).getVal().equals("*")) {
                            tipo_f += "*";
                        }
                    } else if (hijo.getVal().equals("ID")) {
                        id_f += hijo.getHijos().get(0).getVal();
                        this.ambito_actual = id_f;
                    } else if (hijo.getVal().equals("p") || hijo.getVal().equals("#")) {
                        if (!"".equals(tipo_f)) {
                            ArrayList<Variable> v = parametros(hijo, new ArrayList<>());
                            Funcion func = (new Funcion(tipo_f, id_f));
                            func.agregar_params(v);
                            if (verificar_decfunc(id_f)) {
                                this.decfunciones.add(func);
                            } else {
                                //System.out.println("La funcion " + id_f + " fue definida más de una vez.");
                                this.errores_semanticos.add("La funcion " + id_f + " fue definida más de una vez.");
                            }

                            tipo_f = "";
                            id_f = "";
                        }
                    } else {
                        recorrer(hijo);
                    }
                }
            } else if (nodo.getVal().equals("Exp")) {
                this.variables.clear();
                this.constantes.clear();
                this.operadores.clear();
                variables_expresion(nodo);
                boolean ambitos = true;
                for (int i = 0; i < this.variables.size(); i++) {
                    if (!verificar_variables_exp(this.variables.get(i))) {
                        //System.out.println("La variable " + variables.get(i) + " No existe o no está en la funcion " + this.ambito_actual);
                        this.errores_semanticos.add("La variable " + variables.get(i) + " No existe o no está en la funcion " + this.ambito_actual);
                        ambitos = false;
                    }
                }
                boolean rel = false;
                if (this.operadores.size() > 0) {
                    String first = this.operadores.get(0);
                    if (!(first.equals("*") || first.equals("/") || first.equals("+") || first.equals("-"))) {
                        rel = true;
                    }
                }
                boolean type = false;
                if (rel) {
                    for (int i = 1; i < this.operadores.size(); i++) {
                        String j = this.operadores.get(i);
                        if (j.equals("*") || j.equals("/") || j.equals("+") || j.equals("-")) {
                            type = true;
                        }
                    }
                } else {
                    for (int i = 1; i < this.operadores.size(); i++) {
                        String j = this.operadores.get(i);
                        if (!(j.equals("*") || j.equals("/") || j.equals("+") || j.equals("-"))) {
                            type = true;
                        }
                    }
                }
                if (type) {
                    this.errores_semanticos.add("Expresión en la función " + this.ambito_actual + " combina aritmeticas y booleanas");
                } else {
                    if (rel) {
                        nodo.setVal("ExpBool");
                    }
                }
                if (ambitos) {
                    ArrayList<Variable> tipos = new ArrayList<>();
                    for (int i = 0; i < this.variables.size(); i++) {
                        String v = this.variables.get(i);
                        boolean pointer = false;
                        boolean ampersant = false;
                        if (v.charAt(0) == '*') {
                            v = v.substring(1);
                            pointer = true;
                        }
                        if (v.charAt(0) == '&') {
                            v = v.substring(1);
                            ampersant = true;
                        }
                        boolean global = true;
                        for (int j = 0; j < this.tabla.size(); j++) {
                            if (v.equals(this.tabla.get(j).getId()) && (this.tabla.get(j).getAmbito().equals(this.ambito_actual))) {
                                global = false;
                                if (pointer) {
                                    if (this.tabla.get(j).getTipo().contains("*")) {
                                        Variable vai = new Variable(this.tabla.get(j).getTipo(), this.tabla.get(j).getId(), this.tabla.get(j).getAmbito());
                                        vai.setTipo(vai.getTipo().substring(0, vai.getTipo().length() - 1));
                                        tipos.add(vai);
                                    } else {
                                        //System.out.println("Está intentando usar * en una variable que no es pointer " + this.tabla.get(j).getId());
                                        this.errores_semanticos.add("Está intentando usar * en una variable que no es pointer " + this.tabla.get(j).getId());
                                    }
                                } else if (ampersant) {
                                    if (!this.tabla.get(j).getTipo().contains("*")) {
                                        Variable vai = new Variable(this.tabla.get(j).getTipo(), this.tabla.get(j).getId(), this.tabla.get(j).getAmbito());
                                        vai.setTipo(vai.getTipo() + "*");
                                        tipos.add(vai);
                                    } else {
                                        //System.out.println("Está intentando usar * en una variable que no es pointer " + this.tabla.get(j).getId());
                                        this.errores_semanticos.add("Está intentando usar & en una variable es pointer " + this.tabla.get(j).getId());
                                    }
                                } else {
                                    tipos.add(this.tabla.get(j));
                                }

                            }
                        }
                        if (global) {
                            for (int j = 0; j < this.tabla.size(); j++) {
                                if (v.equals(this.tabla.get(j).getId()) && (this.tabla.get(j).getAmbito().equals("1Global"))) {
                                    global = false;
                                    if (pointer) {
                                        if (this.tabla.get(j).getTipo().contains("*")) {
                                            Variable vai = new Variable(this.tabla.get(j).getTipo(), this.tabla.get(j).getId(), this.tabla.get(j).getAmbito());
                                            vai.setTipo(vai.getTipo().substring(0, vai.getTipo().length() - 1));
                                            tipos.add(vai);
                                        } else {
                                            //System.out.println("Está intentando usar * en una variable que no es pointer " + this.tabla.get(j).getId());
                                            this.errores_semanticos.add("Está intentando usar * en una variable que no es pointer " + this.tabla.get(j).getId());
                                        }
                                    } else if (ampersant) {
                                        if (!this.tabla.get(j).getTipo().contains("*")) {
                                            Variable vai = new Variable(this.tabla.get(j).getTipo(), this.tabla.get(j).getId(), this.tabla.get(j).getAmbito());
                                            vai.setTipo(vai.getTipo() + "*");
                                            tipos.add(vai);
                                        } else {
                                            //System.out.println("Está intentando usar * en una variable que no es pointer " + this.tabla.get(j).getId());
                                            this.errores_semanticos.add("Está intentando usar & en una variable es pointer " + this.tabla.get(j).getId());
                                        }
                                    } else {
                                        tipos.add(this.tabla.get(j));
                                    }

                                }
                            }
                        }
                    }
                    String tipo_1 = "";
                    if (tipos.size() > 0) {
                        tipo_1 = tipos.get(0).getTipo();
                    }

                    boolean tipos_iguales = true;
                    for (int i = 1; i < tipos.size(); i++) {
                        if (!tipos.get(i).getTipo().equals(tipo_1)) {
                            tipos_iguales = false;
                            //System.out.println("Error de tipos: Funcion " + this.ambito_actual + " variable " + tipos.get(i).getId());
                            this.errores_semanticos.add("Error de tipos: Funcion " + this.ambito_actual + " variable " + tipos.get(i).getId());
                        }
                    }
                    if (!tipo_1.equals("")) {
                        for (int i = 0; i < this.constantes.size(); i++) {
                            if (!this.constantes.get(i).equals(tipo_1)) {
                                tipos_iguales = false;
                                //System.out.println("Error de tipos: Funcion " + this.ambito_actual + " constante " + this.constantes.get(i));
                                this.errores_semanticos.add("Error de tipos: Funcion " + this.ambito_actual + " constante " + this.constantes.get(i));
                            }
                        }
                    } else {
                        if (this.constantes.size() > 0) {
                            tipo_1 = this.constantes.get(0);
                        }
                        for (int i = 1; i < this.constantes.size(); i++) {
                            if (!this.constantes.get(i).equals(tipo_1)) {
                                tipos_iguales = false;
                                //System.out.println("Error de tipos: Funcion " + this.ambito_actual + " constante " + this.constantes.get(i));
                                this.errores_semanticos.add("Error de tipos: Funcion " + this.ambito_actual + " constante " + this.constantes.get(i));
                            }
                        }
                    }
                    if (this.return_flag) {
                        if (!tipo_1.equals(this.tipo_actual)) {
                            //System.out.println("El tipo del return en la funcion " + this.ambito_actual + " no corresponde.");
                            this.errores_semanticos.add("El tipo del return en la funcion " + this.ambito_actual + " no corresponde.");
                        }
                        this.return_flag = false;
                    }
                    if (this.printf_flag) {
                        if (!tipo_1.equals(this.printf_tipo)) {
                            this.errores_semanticos.add("El tipo del printf en la funcion " + this.ambito_actual + " no corresponde.");
                        }
                        this.printf_flag = false;
                    }
                    if (this.asig_flag) {
                        if (!tipo_1.equals(this.asig_tipo)) {
                            this.errores_semanticos.add("El tipo de la asignacion en la funcion " + this.ambito_actual + " no corresponde.");
                        }
                        this.asig_flag = false;
                    }
                }

            } else if (nodo.getVal().equals("DecGlobal")) {
                String tipo = "";
                String id = "";
                for (TreeNode hijo : nodo.getHijos()) {
                    if (hijo.getVal().equals("Tipo")) {
                        tipo = hijo.getHijos().get(0).getVal();
                        if (hijo.getHijos().get(1).getVal().equals("*")) {
                            tipo += "*";
                        }
                    } else if (hijo.getVal().equals("*")) {
                        tipo += "*";
                    } else if (hijo.getVal().equals("ID")) {
                        id += hijo.getHijos().get(0).getVal();
                        if (verificar_variable_global(id)) {
                            //System.out.println("Error Semántico: La variable '" + id + "' ha sido declarada más de una vez");
                            this.errores_semanticos.add("Error Semántico: La variable '" + id + "' ha sido declarada más de una vez");
                        } else {
                            this.tabla.add(new Variable(tipo, id, "1Global"));
                        }
                        if (tipo.contains("*")) {
                            tipo = tipo.substring(0, tipo.length() - 1);
                        }
                        id = "";
                    }
                }
            } else if (nodo.getVal().equals("return")) {
                this.return_flag = true;
                recorrer(nodo.getHijos().get(0));
            } else if (nodo.getVal().equals("Printf")) {
                String cadena = nodo.getHijos().get(0).getVal();
                String acum = "";
                this.printf_tipo = "";
                int cont = 0;
                for (int i = 0; i < cadena.length(); i++) {
                    if (cadena.charAt(i) == '%') {
                        acum += '%';
                    } else if (cadena.charAt(i) == 'd' || cadena.charAt(i) == 'c') {
                        if (acum.length() > 0) {
                            cont++;
                            acum = "";
                            if (cadena.charAt(i) == 'd') {
                                this.printf_tipo = "int";
                            } else {
                                this.printf_tipo = "char";
                            }
                        }
                    }
                }
                if (cont > 1) {
                    this.errores_semanticos.add("Printf en la funcion " + this.ambito_actual + " espera más parametros de los que requiere.");
                } else if (cont == 0 && !nodo.getHijos().get(1).getVal().equals("#")) {
                    this.errores_semanticos.add("Printf en la funcion " + this.ambito_actual + " contiene más parámetros de lo esperado.");
                } else if (cont == 1 && nodo.getHijos().get(1).getVal().equals("#")) {
                    this.errores_semanticos.add("Printf en la funcion " + this.ambito_actual + " no contiene el parámetro esperado.");
                } else if (cont == 0 && nodo.getHijos().get(1).getVal().equals("#")) {

                } else {
                    this.printf_flag = true;
                    recorrer(nodo.getHijos().get(1));
                }
            } else if (nodo.getVal().equals("Scanf")) {
                String cadena = nodo.getHijos().get(0).getVal();
                String ampersant = nodo.getHijos().get(1).getVal();
                String id = nodo.getHijos().get(2).getHijos().get(0).getVal();
                String tipo_scan = "";
                if (cadena.equals("%d") || cadena.equals("%c")) {
                    if (cadena.equals("%d")) {
                        tipo_scan = "int";
                    } else {
                        tipo_scan = "char";
                    }
                    if (ampersant.equals("#")) {
                        tipo_scan += "*";
                    }
                    if (verificar_variable(id)) {
                        System.out.println("TIPO DE " + id + " " + tipo_var(id));
                        System.out.println("Tipo DE scanf" + tipo_scan);
                        if (!tipo_scan.equals(tipo_var(id))) {
                            this.errores_semanticos.add("Los tipos en el scanf de la funcion " + this.ambito_actual + " no concuerdan");
                        }
                    } else {
                        this.errores_semanticos.add("La variable " + id + " en el Scanf en la funcion " + this.ambito_actual + " no existe");
                    }
                } else {
                    this.errores_semanticos.add("Scanf en la funcion " + this.ambito_actual + " debe ser %d o %c");
                }
            } else if (nodo.getVal().equals("Asig")) {
                String variable = nodo.getHijos().get(0).getHijos().get(0).getVal();
                if (!verificar_variables_exp(variable)) {
                    this.errores_semanticos.add("La variable " + variable + " No existe o no está en la funcion " + this.ambito_actual);
                } else {
                    this.asig_flag = true;
                    this.asig_tipo = tipo_var(variable);
                    recorrer(nodo.getHijos().get(1));
                }
            } else {
                for (TreeNode hijo : nodo.getHijos()) {
                    recorrer(hijo);
                }
            }
        }
    }

    public ArrayList<Variable> parametros(TreeNode tn, ArrayList<Variable> arr) {
        if (!tn.getHijos().isEmpty()) {
            for (TreeNode hijo : tn.getHijos()) {
                if (hijo.getVal().equals("Tipo")) {
                    Variable v = new Variable(hijo.getHijos().get(0).getVal(), "", this.ambito_actual);
                    if (!"#".equals(hijo.getHijos().get(1).getVal())) {
                        v.setTipo(v.getTipo() + "*");
                    }
                    v.setOffset(this.offset);
                    if (v.getTipo().equals("char")) {
                        this.offset += 1;
                    } else {
                        this.offset += 4;
                    }
                    arr.add(v);
                } else if (hijo.getVal().equals("ID")) {
                    arr.get(arr.size() - 1).setId(hijo.getHijos().get(0).getVal());
                } else if (hijo.getVal().equals("p")) {
                    return parametros(hijo, arr);
                }
            }
        }
        return arr;
    }

    public boolean verificar_variable(String variable) {
        boolean ret = false;
        for (int i = 0; i < this.tabla.size(); i++) {
            if (variable.equals(this.tabla.get(i).getId()) && this.ambito_actual.equals(this.tabla.get(i).getAmbito())) {
                ret = true;
            }
        }
        return ret;
    }

    public boolean verificar_variable_global(String variable) {
        boolean ret = false;
        for (int i = 0; i < this.tabla.size(); i++) {
            if (variable.equals(this.tabla.get(i).getId()) && ("1Global").equals(this.tabla.get(i).getAmbito())) {
                ret = true;
            }
        }
        for (int i = 0; i < this.funciones.size(); i++) {
            if (variable.equals(this.funciones.get(i).getId())) {
                ret = true;
            }
        }
        for (int i = 0; i < this.decfunciones.size(); i++) {
            if (variable.equals(this.decfunciones.get(i).getId())) {
                ret = true;
            }
        }
        return ret;
    }

    public boolean verificar_variables_exp(String v) {
        boolean ret = false;
        if (v.charAt(0) == '*' || v.charAt(0) == '&') {
            v = v.substring(1);
        }
        for (int i = 0; i < this.tabla.size(); i++) {
            if (this.tabla.get(i).getId().equals(v) && (this.tabla.get(i).getAmbito().equals(this.ambito_actual) || this.tabla.get(i).getAmbito().equals("1Global"))) {
                ret = true;
            }
        }
        return ret;
    }

    public void variables_expresion(TreeNode root) {
        for (TreeNode hijo : root.getHijos()) {
            if (hijo.getVal().equals("ID")) {
                if (hijo.getHijos().get(0).getVal().equals("*")) {
                    this.variables.add("*" + hijo.getHijos().get(1).getVal());
                } else if (hijo.getHijos().get(0).getVal().equals("&")) {
                    this.variables.add("&" + hijo.getHijos().get(1).getVal());
                } else {
                    this.variables.add(hijo.getHijos().get(0).getVal());
                }
            } else if (hijo.getVal().equals("#")) {
            } else if (hijo.getVal().equals("Num")) {
                this.constantes.add("int");
            } else if (hijo.getVal().equals("ConstChar")) {
                this.constantes.add("char");
            } else if (hijo.getVal().equals("Funccall")) {
                String f = hijo.getHijos().get(0).getHijos().get(0).getVal();
                boolean exist = false;
                for (int i = 0; i < this.funciones.size(); i++) {
                    if (f.equals(this.funciones.get(i).getId())) {
                        this.constantes.add(this.funciones.get(i).tipo);
                        exist = true;
                    }
                }
                if (!exist) {
                    //System.out.println("La funcion " + f + " no existe");
                    this.errores_semanticos.add("La funcion " + f + " no existe");
                }
                this.funccall.clear();
                funcion(hijo.getHijos().get(1));

                ArrayList<String> argumentos = new ArrayList<>();
                for (int i = 0; i < this.funccall.size(); i++) {
                    String tipo = "";
                    boolean same = true;
                    for (int j = 0; j < this.funccall.get(i).size(); j++) {
                        if (j == 0) {
                            tipo = this.funccall.get(i).get(j);
                            if (!"int".equals(tipo) && !"char".equals(tipo)) {
                                tipo = tipo_var(tipo);
                            }
                        } else {
                            if (!this.funccall.get(i).get(j).equals("int") && !this.funccall.get(i).get(j).equals("char")) {
                                String val = tipo_var(this.funccall.get(i).get(j));
                                if (!val.equals(tipo)) {
                                    same = false;
                                }
                            }
                        }
                    }
                    if (same) {
                        argumentos.add(tipo);
                    } else {
                        argumentos.add("#");
                        //System.out.println("La expresión " + i + " No sirve");
                        this.errores_semanticos.add("La expresión " + i + " No sirve");
                    }
                }
                Funcion func = new Funcion("", "");
                for (int i = 0; i < this.funciones.size(); i++) {
                    if (f.equals(this.funciones.get(i).getId())) {
                        func = this.funciones.get(i);
                    }
                }
                boolean correct = true;
                if (func.getParams().size() == argumentos.size()) {
                    for (int i = 0; i < argumentos.size(); i++) {
                        if (!func.getParams().get(i).getTipo().equals(argumentos.get(i))) {
                            correct = false;
                        }
                    }
                } else {
                    correct = false;
                }
                if (!correct && exist) {
                    //System.out.println("Los parametros al llamado a al función " + f + " son incorrectos.");
                    this.errores_semanticos.add("Los parametros al llamado a al función " + f + " son incorrectos.");
                }

            } else {
                if (!(hijo.getVal().equals("Exp"))) {
                    this.operadores.add(hijo.getVal());
                }
                variables_expresion(hijo);
            }
        }
    }

    public void funcion(TreeNode root) {
        if (!root.getHijos().isEmpty()) {
            for (TreeNode hijo : root.getHijos()) {
                if (hijo.getVal().equals("Exp")) {
                    this.funccall.add(new ArrayList<>());
                    funcion(hijo);
                } else if (hijo.getVal().equals("Num")) {
                    this.funccall.get(this.funccall.size() - 1).add("int");
                } else if (hijo.getVal().equals("ID")) {
                    this.funccall.get(this.funccall.size() - 1).add(hijo.getHijos().get(0).getVal());
                } else if (hijo.getVal().equals("ConstChar")) {
                    this.funccall.get(this.funccall.size() - 1).add("char");
                } else {
                    funcion(hijo);
                }
            }
        }
    }

    public int verificar_main() {
        int cont = 0;
        for (int i = 0; i < this.funciones.size(); i++) {
            if (this.funciones.get(i).getId().equals("main")) {
                cont++;
            }
        }
        return cont;
    }

    public boolean verificar_funcion(String id) {
        boolean ret = true;
        for (int i = 0; i < this.funciones.size(); i++) {
            if (this.funciones.get(i).getId().equals(id)) {
                ret = false;
            }
        }
        for (int i = 0; i < this.tabla.size(); i++) {
            if (this.tabla.get(i).getId().equals(id) && this.tabla.get(i).getAmbito().equals("1Global")) {
                ret = false;
            }
        }
        return ret;
    }

    public boolean verificar_decfunc(String id) {
        boolean ret = true;
        for (int i = 0; i < this.decfunciones.size(); i++) {
            if (this.decfunciones.get(i).getId().equals(id)) {
                ret = false;
            }
        }
        //esto agregué
        for (int i = 0; i < this.tabla.size(); i++) {
            if (this.tabla.get(i).getId().equals(id) && this.tabla.get(i).getAmbito().equals("1Global")) {
                ret = false;
            }
        }
        return ret;
    }

    public String tipo_var(String id) {
        String ret = "";
        for (int i = 0; i < this.tabla.size(); i++) {
            if (this.tabla.get(i).getId().equals(id)) {
                ret = this.tabla.get(i).getTipo();
            }
        }
        return ret;
    }

    //Codigo intermedio
    public void codigo_intermedio(TreeNode tn) {
        TreeNode nodo = tn;
        if (nodo != null) {
            switch (nodo.getVal()) {
                case "Funcion":
                    String nombre = nodo.getHijos().get(1).getHijos().get(0).getVal();
                    this.cuadruplos.add(new Cuadruplo("Func", nombre, "", ""));
                    nodo.getHijos().forEach((hijo) -> {
                        codigo_intermedio(hijo);
                    });
                    break;
                case "Statement":
                    nodo.setSiguiente(nuevaEtiqueta());
                    nodo.getHijos().forEach((hijo) -> {
                        codigo_intermedio(hijo);
                        if (hijo.getVal().equals("IF") || hijo.getVal().equals("While") || hijo.getVal().equals("For")) {
                            this.cuadruplos.add(new Cuadruplo("ETIQ", nodo.getSiguiente(), "", ""));
                            nodo.setSiguiente(nuevaEtiqueta());
                        }
                    });
                    break;
                case "IF":
                    if (nodo.getHijos().get(2).getVal().equals("#")) {
                        nodo.getHijos().get(0).setVerdadero(nuevaEtiqueta());
                        nodo.getHijos().get(0).setFalso(nodo.padre.getSiguiente());
                        codigo_intermedio(nodo.getHijos().get(0));
                        this.cuadruplos.add(new Cuadruplo("ETIQ", nodo.getHijos().get(0).getVerdadero(), "", ""));
                        codigo_intermedio(nodo.getHijos().get(1));
                    } else {
                        nodo.getHijos().get(0).setVerdadero(nuevaEtiqueta());
                        nodo.getHijos().get(0).setFalso(nuevaEtiqueta());
                        codigo_intermedio(nodo.getHijos().get(0));
                        this.cuadruplos.add(new Cuadruplo("ETIQ", nodo.getHijos().get(0).getVerdadero(), "", ""));
                        codigo_intermedio(nodo.getHijos().get(1));
                        this.cuadruplos.add(new Cuadruplo("GOTO", nodo.padre.getSiguiente(), "", ""));
                        this.cuadruplos.add(new Cuadruplo("ETIQ", nodo.getHijos().get(0).getFalso(), "", ""));
                        codigo_intermedio(nodo.getHijos().get(2));
                    }
                    break;
                case "While":
                    nodo.setComienzo(nuevaEtiqueta());
                    nodo.getHijos().get(0).setVerdadero(nuevaEtiqueta());
                    nodo.getHijos().get(0).setFalso(nodo.padre.getSiguiente());     //pasar etiquetas al hijo
                    this.cuadruplos.add(new Cuadruplo("ETIQ", nodo.getComienzo(), "", ""));    // crear etiqueta comienzo
                    codigo_intermedio(nodo.getHijos().get(0));
                    this.cuadruplos.add(new Cuadruplo("ETIQ", nodo.getHijos().get(0).getVerdadero(), "", ""));    // crear etiqueta verdadera
                    codigo_intermedio(nodo.getHijos().get(1));
                    this.cuadruplos.add(new Cuadruplo("GOTO", nodo.getComienzo(), "", ""));
                    break;
                case "For":
                    nodo.setComienzo(nuevaEtiqueta());
                    codigo_intermedio(nodo.getHijos().get(0));
                    nodo.getHijos().get(1).setVerdadero(nuevaEtiqueta());
                    nodo.getHijos().get(1).setFalso(nodo.padre.getSiguiente());
                    this.cuadruplos.add(new Cuadruplo("ETIQ", nodo.getComienzo(), "", ""));
                    codigo_intermedio(nodo.getHijos().get(1));
                    String etiq_exp = nuevaEtiqueta();
                    this.cuadruplos.add(new Cuadruplo("ETIQ", etiq_exp, "", ""));
                    codigo_intermedio(nodo.getHijos().get(2));
                    this.cuadruplos.add(new Cuadruplo("GOTO", nodo.getComienzo(), "", ""));
                    this.cuadruplos.add(new Cuadruplo("ETIQ", nodo.getHijos().get(1).getVerdadero(), "", ""));
                    codigo_intermedio(nodo.getHijos().get(3));
                    this.cuadruplos.add(new Cuadruplo("GOTO", etiq_exp, "", ""));
                    break;
                case "Exp":
                    this.exp_intermedio.clear();
                    expresion_arreglo(nodo);
                    this.exp_intermedio.remove(this.exp_intermedio.size() - 1);
                    this.exp_intermedio.remove(0);
                    operacion();
                    break;
                case "ExpBool":
                    this.exp_bool.clear();
                    bool_arreglo(nodo);
                    this.exp_bool.remove(this.exp_bool.size() - 1);
                    this.exp_bool.remove(0);
                    for (int i = 0; i < this.exp_bool.size(); i++) {
                        System.out.println("[" + this.exp_bool.get(i) + "]");
                    }
                    TreeNode root = arbol_bool();
                    root.setVerdadero(nodo.getVerdadero());
                    root.setFalso(nodo.getFalso());
                    print_bool(root);
                    generar_expbool(root);
                    break;
                case "Scanf":
                    this.cuadruplos.add(new Cuadruplo("Scanf", nodo.getHijos().get(0).getVal(), nodo.getHijos().get(2).getHijos().get(0).getVal(), ""));
                    break;
                case "Printf":
                    if (nodo.getHijos().get(1).getVal().equals("#")) {
                        this.cuadruplos.add(new Cuadruplo("Print", nodo.getHijos().get(0).getVal(), "", ""));
                    } else {
                        this.int_print_flag = true;
                        this.int_print_value = nodo.getHijos().get(0).getVal();
                        codigo_intermedio(nodo.getHijos().get(1));
                    }
                    break;
                case "return":
                    this.int_ret_flag = true;
                    codigo_intermedio(nodo.getHijos().get(0));
                    break;
                case "Asig":
                    this.int_asig_flag = true;
                    this.int_asig_value = nodo.getHijos().get(0).getHijos().get(0).getVal();
                //codigo_intermedio(nodo.getHijos().get(1));
                default:
                    nodo.getHijos().forEach((hijo) -> {
                        codigo_intermedio(hijo);
                    });
            }
        }
    }

    public void expresion_arreglo(TreeNode tn) {
        TreeNode nodo = tn;
        if (nodo != null) {
            switch (nodo.getVal()) {
                case "ID":
                    if (nodo.getHijos().get(0).getVal().equals("*") || nodo.getHijos().get(0).getVal().equals("&")) {
                        this.exp_intermedio.add(nodo.getHijos().get(1).getVal());
                    } else if (nodo.getHijos().get(1).getVal().equals("++")) {
                        //this.exp_intermedio.add("(");
                        this.exp_intermedio.add(nodo.getHijos().get(0).getVal() + "++");
                        //this.exp_intermedio.add("+");
                        //this.exp_intermedio.add("1");
                        //this.exp_intermedio.add(")");
                    } else if (nodo.getHijos().get(1).getVal().equals("--")) {
                        //this.exp_intermedio.add("(");
                        this.exp_intermedio.add(nodo.getHijos().get(0).getVal() + "--");
                        //this.exp_intermedio.add("-");
                        //this.exp_intermedio.add("1");
                        //this.exp_intermedio.add(")");
                    } else {
                        this.exp_intermedio.add(nodo.getHijos().get(0).getVal());
                    }
                    break;
                case "Num":
                    this.exp_intermedio.add(nodo.getHijos().get(0).getVal());
                    break;
                case "ConstChar":
                    this.exp_intermedio.add(nodo.getHijos().get(0).getVal());
                    break;
                case "Exp":
                    this.exp_intermedio.add("(");
                    for (TreeNode hijo : nodo.getHijos()) {
                        expresion_arreglo(hijo);
                    }
                    this.exp_intermedio.add(")");
                    break;
                case "Funccall":
                    System.out.println("A ver");
                    this.exp_intermedio.add(nodo.getHijos().get(0).getHijos().get(0).getVal());
                    break;
                default:
                    if (!nodo.getVal().equals("#")) {
                        this.exp_intermedio.add(nodo.getVal());
                        for (TreeNode hijo : nodo.getHijos()) {
                            expresion_arreglo(hijo);
                        }
                    }
            }
        }

    }

    public void bool_arreglo(TreeNode tn) {
        TreeNode nodo = tn;
        if (nodo != null) {
            switch (nodo.getVal()) {
                case "ID":
                    if (nodo.getHijos().get(0).getVal().equals("*") || nodo.getHijos().get(0).getVal().equals("&")) {
                        this.exp_bool.add(nodo.getHijos().get(1).getVal());
                    } else {
                        this.exp_bool.add(nodo.getHijos().get(0).getVal());
                    }
                    break;
                case "Num":
                    this.exp_bool.add(nodo.getHijos().get(0).getVal());
                    break;
                case "ConstChar":
                    this.exp_bool.add(nodo.getHijos().get(0).getVal());
                    break;
                case "Exp":
                case "ExpBool":
                    this.exp_bool.add("(");
                    for (TreeNode hijo : nodo.getHijos()) {
                        bool_arreglo(hijo);
                    }
                    this.exp_bool.add(")");
                    break;
                default:
                    if (!nodo.getVal().equals("#")) {
                        this.exp_bool.add(nodo.getVal());
                        for (TreeNode hijo : nodo.getHijos()) {
                            bool_arreglo(hijo);
                        }
                    }
                    break;
            }
        }
    }

    public TreeNode arbol_bool() {
        int contadOR = 0;
        int cont = 0;
        TreeNode E = new TreeNode("E", null, ++cont);
        for (int i = 0; i < this.exp_bool.size(); i++) {
            switch (this.exp_bool.get(i)) {
                case "||":
                    if (contadOR == 0) {
                        agregar(E, new TreeNode("E", null, ++cont));
                        agregar(E, new TreeNode("E", null, ++cont));
                        agregar(E, new TreeNode("||", null, ++cont));
                        agregar(E, new TreeNode("E", null, ++cont));
                        contadOR++;
                    } else {
                        agregar(E, new TreeNode("E", null, ++cont));
                        agregar(E, new TreeNode("||", null, ++cont));
                        agregar(E, new TreeNode("E", null, ++cont));
                    }
                    break;
                case "&&":
                    if (contadOR == 0) {
                        agregar(E, new TreeNode("E", null, ++cont));
                        agregar(E, new TreeNode("&&", null, ++cont));
                        agregar(E, new TreeNode("E", null, ++cont));
                    } else {
                        agregar(E, new TreeNode("&&", null, ++cont));
                        agregar(E, new TreeNode("E", null, ++cont));
                    }
                    contadOR = 0;
                    break;
                default:
            }
        }
        int contV = 1;
        TreeNode a1 = new TreeNode("E", null, 0), a2 = new TreeNode("E", null, 0), a3;
        for (int i = 0; i < this.exp_bool.size(); i++) {
            if (!(this.exp_bool.get(i).equals("&&") || this.exp_bool.get(i).equals("||"))) {
                switch (contV) {
                    case 1:
                        a1 = new TreeNode(this.exp_bool.get(i), null, ++cont);
                        contV++;
                        break;
                    case 2:
                        a2 = new TreeNode(this.exp_bool.get(i), null, ++cont);
                        contV++;
                        break;
                    case 3:
                        a3 = new TreeNode(this.exp_bool.get(i), null, ++cont);
                        this.agrega = true;
                        agregar_hoja(E, a1, a2, a3);
                        contV = 1;
                        break;
                }
            }
        }
        return E;
    }

    public void agregar(TreeNode tn, TreeNode value) {
        TreeNode nodo = tn;
        switch (value.getVal()) {
            case "E":
                if (nodo.getHijos().isEmpty()) {
                    nodo.agregarHijo(value);
                } else {
                    switch (nodo.getHijos().size()) {
                        case 2:
                            nodo.agregarHijo(value);
                            break;
                        case 1:
                            agregar(nodo.getHijos().get(0), value);
                            break;
                        case 3:
                            agregar(nodo.getHijos().get(2), value);
                            break;
                        default:
                            break;
                    }
                }
                break;
            case "||":
                if (!nodo.getHijos().isEmpty()) {
                    if (nodo.getHijos().size() == 1) {
                        if (!nodo.getHijos().get(0).getHijos().isEmpty()) {
                            agregar(nodo.getHijos().get(0), value);
                        } else {
                            nodo.agregarHijo(value);
                        }
                    } else {
                        agregar(nodo.getHijos().get(2), value);
                    }
                }
                break;
            case "&&":
                if (nodo.getHijos().size() == 1) {
                    nodo.agregarHijo(value);
                } else {
                    agregar(nodo.getHijos().get(2), value);
                }
                break;
            default:
        }
    }

    public void agregar_hoja(TreeNode tn, TreeNode a1, TreeNode a2, TreeNode a3) {
        TreeNode nodo = tn;

        if (nodo.getHijos().isEmpty() && nodo.getVal().equals("E") && this.agrega) {
            nodo.agregarHijo(a1);
            nodo.agregarHijo(a2);
            nodo.agregarHijo(a3);
            this.agrega = false;
        } else {
            for (TreeNode hijo : nodo.getHijos()) {
                agregar_hoja(hijo, a1, a2, a3);
            }
        }
    }

    public void generar_expbool(TreeNode tn) {
        TreeNode nodo = tn;
        if (nodo != null) {

            if (!nodo.getHijos().isEmpty()) {
                if (nodo.getHijos().size() == 1) {
                    nodo.getHijos().get(0).setVerdadero(nodo.getVerdadero());
                    nodo.getHijos().get(0).setFalso(nodo.getFalso());
                    generar_expbool(nodo.getHijos().get(0));
                } else {
                    switch (nodo.getHijos().get(1).getVal()) {
                        case "&&":
                            nodo.getHijos().get(0).setVerdadero(nuevaEtiqueta());
                            nodo.getHijos().get(0).setFalso(nodo.getFalso());
                            generar_expbool(nodo.getHijos().get(0));

                            this.cuadruplos.add(new Cuadruplo("ETIQ", nodo.getHijos().get(0).getVerdadero(), "", ""));
                            nodo.getHijos().get(2).setVerdadero(nodo.getVerdadero());
                            nodo.getHijos().get(2).setFalso(nodo.getFalso());

                            generar_expbool(nodo.getHijos().get(2));
                            break;
                        case "||":
                            nodo.getHijos().get(0).setVerdadero(nodo.getVerdadero());
                            nodo.getHijos().get(0).setFalso(nuevaEtiqueta());
                            generar_expbool(nodo.getHijos().get(0));

                            this.cuadruplos.add(new Cuadruplo("ETIQ", nodo.getHijos().get(0).getFalso(), "", ""));
                            nodo.getHijos().get(2).setVerdadero(nodo.getVerdadero());
                            nodo.getHijos().get(2).setFalso(nodo.getFalso());

                            generar_expbool(nodo.getHijos().get(2));
                            break;
                        default:
                            String operador = nodo.getHijos().get(1).getVal();
                            String arg1 = nodo.getHijos().get(0).getVal();
                            String arg2 = nodo.getHijos().get(2).getVal();
                            this.cuadruplos.add(new Cuadruplo("IF" + operador, arg1, arg2, nodo.getVerdadero()));
                            this.cuadruplos.add(new Cuadruplo("GOTO", nodo.getFalso(), "", ""));
                            break;
                    }
                }
            }
        }
    }

    public void print_bool(TreeNode tn) {
        TreeNode nodo = tn;
        if (nodo != null) {
            System.out.println("Nodo: " + nodo.getVal() + "" + nodo.id);
            for (TreeNode h : nodo.getHijos()) {
                System.out.println("    hijo: " + h.getVal() + "" + h.id);
            }
            for (TreeNode hijo : nodo.getHijos()) {
                print_bool(hijo);
            }
        }
    }

    public void operacion() {
        String acum = "";
        Stack<String> s = new Stack();
        for (int i = 0; i < this.exp_intermedio.size(); i++) {
            if (this.exp_intermedio.get(i).equals("+") || this.exp_intermedio.get(i).equals("-")) {
                if (s.size() >= 3) {
                    String op, arg1, arg2, res;
                    arg2 = s.pop();
                    op = s.pop();
                    arg1 = s.pop();
                    if (arg2.equals("(") || op.equals("(") || arg1.equals("(")) {
                        s.push(arg1);
                        s.push(op);
                        s.push(arg2);
                        s.push(this.exp_intermedio.get(i));
                    } else {
                        //
                        if (arg1.contains("++")) {
                            String temp = generarTemp();
                            arg1 = arg1.substring(0, arg1.length() - 2);
                            this.cuadruplos.add(new Cuadruplo("+", arg1, "1", temp));
                            this.cuadruplos.add(new Cuadruplo("=", temp, "", arg1));
                        } else if (arg1.contains("--")) {
                            String temp = generarTemp();
                            arg1 = arg1.substring(0, arg1.length() - 2);
                            this.cuadruplos.add(new Cuadruplo("-", arg1, "1", temp));
                            this.cuadruplos.add(new Cuadruplo("=", temp, "", arg1));
                        }
                        if (arg2.contains("++")) {
                            String temp = generarTemp();
                            arg2 = arg2.substring(0, arg2.length() - 2);
                            this.cuadruplos.add(new Cuadruplo("+", arg2, "1", temp));
                            this.cuadruplos.add(new Cuadruplo("=", temp, "", arg2));
                        } else if (arg2.contains("--")) {
                            String temp = generarTemp();
                            arg2 = arg2.substring(0, arg2.length() - 2);
                            this.cuadruplos.add(new Cuadruplo("", arg2, "1", temp));
                            this.cuadruplos.add(new Cuadruplo("=", temp, "", arg2));
                        }
                        res = generarTemp();
                        s.push(res);
                        this.cuadruplos.add(new Cuadruplo(op, arg1, arg2, res));
                        i--;
                    }
                } else {
                    s.push(this.exp_intermedio.get(i));
                }
            } else if (this.exp_intermedio.get(i).equals("*") || this.exp_intermedio.get(i).equals("/")) {
                if (s.size() >= 3) {
                    String temp = s.pop();
                    if (s.peek().equals("+") || s.peek().equals("-")) {
                        s.push(temp);
                        s.push(this.exp_intermedio.get(i));
                    } else {
                        s.push(temp);
                        String op, arg1, arg2, res;
                        arg2 = s.pop();
                        op = s.pop();
                        arg1 = s.pop();
                        if (arg2.equals("(") || op.equals("(") || arg1.equals("(")) {
                            s.push(arg1);
                            s.push(op);
                            s.push(arg2);
                            s.push(this.exp_intermedio.get(i));
                        } else {
                            //
                            if (arg1.contains("++")) {
                                String temp1 = generarTemp();
                                arg1 = arg1.substring(0, arg1.length() - 2);
                                this.cuadruplos.add(new Cuadruplo("+", arg1, "1", temp1));
                                this.cuadruplos.add(new Cuadruplo("=", temp1, "", arg1));
                            } else if (arg1.contains("--")) {
                                String temp1 = generarTemp();
                                arg1 = arg1.substring(0, arg1.length() - 2);
                                this.cuadruplos.add(new Cuadruplo("-", arg1, "1", temp1));
                                this.cuadruplos.add(new Cuadruplo("=", temp1, "", arg1));
                            }
                            if (arg2.contains("++")) {
                                String temp1 = generarTemp();
                                arg2 = arg2.substring(0, arg2.length() - 2);
                                this.cuadruplos.add(new Cuadruplo("+", arg2, "1", temp1));
                                this.cuadruplos.add(new Cuadruplo("=", temp1, "", arg2));
                            } else if (arg2.contains("--")) {
                                String temp1 = generarTemp();
                                arg2 = arg2.substring(0, arg2.length() - 2);
                                this.cuadruplos.add(new Cuadruplo("-", arg2, "1", temp1));
                                this.cuadruplos.add(new Cuadruplo("=", temp1, "", arg2));
                            }
                            res = generarTemp();
                            s.push(res);
                            this.cuadruplos.add(new Cuadruplo(op, arg1, arg2, res));
                            i--;
                        }
                    }
                } else {
                    s.push(this.exp_intermedio.get(i));
                }
            } else if (this.exp_intermedio.get(i).equals(")")) {
                String temp = s.pop();
                if (s.peek().equals("(")) {
                    s.pop();
                    s.push(temp);
                } else {
                    s.push(temp);
                    String op, arg1, arg2, res;
                    arg2 = s.pop();
                    op = s.pop();
                    arg1 = s.pop();
                    //
                    if (arg1.contains("++")) {
                        String temp1 = generarTemp();
                        arg1 = arg1.substring(0, arg1.length() - 2);
                        this.cuadruplos.add(new Cuadruplo("+", arg1, "1", temp1));
                        this.cuadruplos.add(new Cuadruplo("=", temp1, "", arg1));
                    } else if (arg1.contains("--")) {
                        String temp1 = generarTemp();
                        arg1 = arg1.substring(0, arg1.length() - 2);
                        this.cuadruplos.add(new Cuadruplo("-", arg1, "1", temp1));
                        this.cuadruplos.add(new Cuadruplo("=", temp1, "", arg1));
                    }
                    if (arg2.contains("++")) {
                        String temp1 = generarTemp();
                        arg2 = arg2.substring(0, arg2.length() - 2);
                        this.cuadruplos.add(new Cuadruplo("+", arg2, "1", temp1));
                        this.cuadruplos.add(new Cuadruplo("=", temp1, "", arg2));
                    } else if (arg2.contains("--")) {
                        String temp1 = generarTemp();
                        arg2 = arg2.substring(0, arg2.length() - 2);
                        this.cuadruplos.add(new Cuadruplo("-", arg2, "1", temp1));
                        this.cuadruplos.add(new Cuadruplo("=", temp1, "", arg2));
                    }
                    res = generarTemp();
                    s.push(res);
                    this.cuadruplos.add(new Cuadruplo(op, arg1, arg2, res));
                    i--;
                }
            } else {
                s.push(this.exp_intermedio.get(i));
            }
        }
        while (s.size() > 1) {
            if (s.size() >= 3) {
                String op, arg1, arg2, res;

                arg2 = s.pop();
                op = s.pop();
                arg1 = s.pop();
                //
                if (arg1.contains("++")) {
                    String temp1 = generarTemp();
                    arg1 = arg1.substring(0, arg1.length() - 2);
                    this.cuadruplos.add(new Cuadruplo("+", arg1, "1", temp1));
                    this.cuadruplos.add(new Cuadruplo("=", temp1, "", arg1));
                } else if (arg1.contains("--")) {
                    String temp1 = generarTemp();
                    arg1 = arg1.substring(0, arg1.length() - 2);
                    this.cuadruplos.add(new Cuadruplo("-", arg1, "1", temp1));
                    this.cuadruplos.add(new Cuadruplo("=", temp1, "", arg1));
                }
                if (arg2.contains("++")) {
                    String temp1 = generarTemp();
                    arg2 = arg2.substring(0, arg2.length() - 2);
                    this.cuadruplos.add(new Cuadruplo("+", arg2, "1", temp1));
                    this.cuadruplos.add(new Cuadruplo("=", temp1, "", arg2));
                } else if (arg2.contains("--")) {
                    String temp1 = generarTemp();
                    arg2 = arg2.substring(0, arg2.length() - 2);
                    this.cuadruplos.add(new Cuadruplo("-", arg2, "1", temp1));
                    this.cuadruplos.add(new Cuadruplo("=", temp1, "", arg2));
                }
                res = generarTemp();
                s.push(res);
                this.cuadruplos.add(new Cuadruplo(op, arg1, arg2, res));
            }
        }
        //
        if (s.size() == 1) {
            if (s.peek().contains("++")) {
                String temp1 = generarTemp();
                String arg = s.pop();
                arg = arg.substring(0, arg.length() - 2);
                this.cuadruplos.add(new Cuadruplo("+", arg, "1", temp1));
                this.cuadruplos.add(new Cuadruplo("=", temp1, "", arg));
            } else if (s.peek().contains("--")) {
                String temp1 = generarTemp();
                String arg = s.pop();
                arg = arg.substring(0, arg.length() - 2);
                this.cuadruplos.add(new Cuadruplo("-", arg, "1", temp1));
                this.cuadruplos.add(new Cuadruplo("=", temp1, "", arg));
            }
        }
        if (this.int_asig_flag) {
            this.cuadruplos.add(new Cuadruplo("=", s.pop(), "", this.int_asig_value));
            this.int_asig_flag = false;
            this.int_asig_value = "";
        }
        if (this.int_ret_flag) {
            this.cuadruplos.add(new Cuadruplo("RET", s.pop(), "", ""));
            this.int_ret_flag = false;
        }
        if (this.int_print_flag) {
            this.cuadruplos.add(new Cuadruplo("Print", this.int_print_value, s.pop(), ""));
            this.int_print_flag = false;
            this.int_print_value = "";
        }
    }

    public String generarTemp() {
        this.cont_temp++;
        return "t" + this.cont_temp;
    }

    public String nuevaEtiqueta() {
        this.cont_etiq++;
        return "etiq" + this.cont_etiq;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea;
    private javax.swing.JTextArea TextErrores;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JButton bt_probar;
    private javax.swing.JButton bt_seleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable table_cuadruplos;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
    File fichero;
    ArrayList<String> errores_semanticos = new ArrayList();
    ArrayList<Variable> tabla = new ArrayList();
    ArrayList<Funcion> funciones = new ArrayList();
    ArrayList<Funcion> decfunciones = new ArrayList();
    ArrayList<String> variables = new ArrayList();
    ArrayList<String> constantes = new ArrayList();
    ArrayList<String> operadores = new ArrayList();
    ArrayList<ArrayList<String>> funccall = new ArrayList();
    String ambito_actual = "";
    String tipo_actual = "";
    String asig_tipo = "";
    boolean return_flag = false;
    boolean printf_flag = false;
    boolean asig_flag = false;
    String printf_tipo = "";
    int offset = 0;
    //Intermedio
    ArrayList<Cuadruplo> cuadruplos = new ArrayList();
    ArrayList<String> exp_intermedio = new ArrayList();
    ArrayList<String> exp_bool = new ArrayList();
    int cont_temp = 0;
    int cont_etiq = 0;
    boolean int_asig_flag = false;
    boolean int_ret_flag = false;
    boolean int_print_flag = false;
    boolean agrega = true;
    String int_asig_value = "";
    String int_print_value = "";
}
