
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int OPLESSEQ = 30;
  public static final int IDE = 18;
  public static final int OPCOMP = 25;
  public static final int SEMICOLON = 15;
  public static final int CHARACTER = 3;
  public static final int WHILE = 6;
  public static final int SCANF = 9;
  public static final int CONSTSTR = 20;
  public static final int OPDIV = 22;
  public static final int PARINIT = 12;
  public static final int OPGRAEP = 29;
  public static final int IF = 7;
  public static final int COLON = 16;
  public static final int PRINTF = 8;
  public static final int OPGRA = 27;
  public static final int OPMULT = 21;
  public static final int KEYINIT = 10;
  public static final int STRING = 4;
  public static final int COMMA = 14;
  public static final int EOF = 0;
  public static final int OPDIF = 26;
  public static final int OPCOND = 31;
  public static final int CONSTCHAR = 19;
  public static final int error = 1;
  public static final int KEYFIN = 11;
  public static final int OPASIG = 24;
  public static final int INTEGER = 2;
  public static final int OPLESS = 28;
  public static final int OPSUM = 23;
  public static final int FOR = 5;
  public static final int PARFIN = 13;
  public static final int NUMBERS = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "CHARACTER",
  "STRING",
  "FOR",
  "WHILE",
  "IF",
  "PRINTF",
  "SCANF",
  "KEYINIT",
  "KEYFIN",
  "PARINIT",
  "PARFIN",
  "COMMA",
  "SEMICOLON",
  "COLON",
  "NUMBERS",
  "IDE",
  "CONSTCHAR",
  "CONSTSTR",
  "OPMULT",
  "OPDIV",
  "OPSUM",
  "OPASIG",
  "OPCOMP",
  "OPDIF",
  "OPGRA",
  "OPLESS",
  "OPGRAEP",
  "OPLESSEQ",
  "OPCOND"
  };
}

