
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int OPSUM = 26;
  public static final int OPCOND = 34;
  public static final int SCANF = 12;
  public static final int OPLESS = 31;
  public static final int INTEGER = 2;
  public static final int FOR = 7;
  public static final int OPCOMP = 28;
  public static final int CHARACTER = 3;
  public static final int AND = 35;
  public static final int SEMICOLON = 18;
  public static final int OR = 36;
  public static final int COMMA = 17;
  public static final int OPASIG = 27;
  public static final int PARFIN = 16;
  public static final int NUM = 20;
  public static final int MAIN = 4;
  public static final int IF = 9;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int PARINIT = 15;
  public static final int error = 1;
  public static final int OPGRA = 30;
  public static final int CONSTSTR = 23;
  public static final int VOID = 5;
  public static final int KEYFIN = 14;
  public static final int OPDIV = 25;
  public static final int IDE = 21;
  public static final int PRINTF = 11;
  public static final int KEYINIT = 13;
  public static final int COLON = 19;
  public static final int ELSE = 10;
  public static final int WHILE = 8;
  public static final int OPDIF = 29;
  public static final int OPGRAEP = 32;
  public static final int OPLESSEQ = 33;
  public static final int CONSTCHAR = 22;
  public static final int OPMULT = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "CHARACTER",
  "MAIN",
  "VOID",
  "RETURN",
  "FOR",
  "WHILE",
  "IF",
  "ELSE",
  "PRINTF",
  "SCANF",
  "KEYINIT",
  "KEYFIN",
  "PARINIT",
  "PARFIN",
  "COMMA",
  "SEMICOLON",
  "COLON",
  "NUM",
  "IDE",
  "CONSTCHAR",
  "CONSTSTR",
  "OPMULT",
  "OPDIV",
  "OPSUM",
  "OPASIG",
  "OPCOMP",
  "OPDIF",
  "OPGRA",
  "OPLESS",
  "OPGRAEP",
  "OPLESSEQ",
  "OPCOND",
  "AND",
  "OR"
  };
}

